---
# Velero Installation and Configuration Tasks

- name: Create Velero namespace
  shell: /var/lib/rancher/rke2/bin/kubectl create namespace {{ velero_namespace }} --dry-run=client -o yaml | /var/lib/rancher/rke2/bin/kubectl apply -f -
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  tags:
    - velero

- name: Add Velero Helm repository
  shell: |
    export PATH=/usr/local/bin:$PATH
    /usr/local/bin/helm repo add vmware-tanzu https://vmware-tanzu.github.io/helm-charts
    /usr/local/bin/helm repo update
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  tags:
    - velero


- name: Create Velero credentials secret
  shell: |
    /var/lib/rancher/rke2/bin/kubectl -n {{ velero_namespace }} delete secret cloud-credentials --ignore-not-found
    /var/lib/rancher/rke2/bin/kubectl -n {{ velero_namespace }} create secret generic cloud-credentials \
      --from-literal=cloud='[default]\naws_access_key_id={{ velero_s3_access_key }}\naws_secret_access_key={{ velero_s3_secret_key }}'
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  tags:
    - velero

- name: Install Velero via Helm
  shell: |
    export PATH=/usr/local/bin:$PATH
    /usr/local/bin/helm upgrade --install velero vmware-tanzu/velero \
      --namespace {{ velero_namespace }} \
      --version 2.30.2 \
      --set configuration.provider={{ velero_provider }} \
      --set configuration.backupStorageLocation.name=default \
      --set configuration.backupStorageLocation.bucket={{ velero_bucket }} \
      --set configuration.backupStorageLocation.config.s3Url={{ velero_s3_url }} \
      --set configuration.backupStorageLocation.config.region=minio \
      --set credentials.existingSecret=cloud-credentials \
      --set initContainers[0].name=velero-plugin-for-aws \
      --set initContainers[0].image=velero/velero-plugin-for-aws:v1.8.0 \
      --set initContainers[0].volumeMounts[0].mountPath=/target \
      --set initContainers[0].volumeMounts[0].name=plugins \
      --set image.tag=v1.13.2 \
      --wait --timeout=600s
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  tags:
    - velero
  ignore_errors: true

- name: Display Velero status
  shell: /var/lib/rancher/rke2/bin/kubectl get pods -n {{ velero_namespace }}
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  register: velero_status
  tags:
    - velero
  ignore_errors: true

- name: Show Velero pod status
  debug:
    msg: |
      🚀 Velero Deployment Status:
      {{ velero_status.stdout }}
  tags:
    - velero
  ignore_errors: true
